In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf

In [63]:
# url = 'https://raw.githubusercontent.com/mwitiderrick/stockprice/master/NSE-TATAGLOBAL.csv'
# dataset_train = pd.read_csv(url)
# training_set = dataset_train.iloc[:, 1:2].values
#See the yahoo finance ticker for your stock symbol
stock_symbol = 'TATACONSUM.NS'
dataset_train = yf.download(tickers=stock_symbol,period='5y',interval='1d')
training_set = dataset_train.iloc[:, 1:2].values

[*********************100%***********************]  1 of 1 completed


In [64]:
training_set

array([[196.30000305],
       [197.5       ],
       [198.1499939 ],
       ...,
       [813.        ],
       [811.90002441],
       [810.79998779]])

In [61]:
dataset_train.tail(100)

Open        High         Low       Close   Adj Close  \
Date                                                                     
2022-04-04  792.000000  795.000000  781.750000  788.099976  781.802673   
2022-04-05  791.000000  810.000000  788.200012  806.650024  800.204529   
2022-04-06  810.450012  812.500000  797.049988  809.250000  802.783691   
2022-04-07  809.000000  818.299988  802.049988  804.900024  798.468506   
2022-04-08  810.500000  819.849976  804.000000  817.700012  811.166199   
...                ...         ...         ...         ...         ...   
2022-08-22  785.900024  796.950012  780.099976  793.950012  793.950012   
2022-08-23  791.900024  811.650024  787.000000  809.349976  809.349976   
2022-08-24  805.000000  813.000000  798.500000  805.700012  805.700012   
2022-08-25  808.000000  811.900024  797.500000  801.849976  801.849976   
2022-08-26  805.900024  810.799988  798.799988  801.950012  801.950012   

             Volume  
Date                 
2022-04-04  1565651  
2022-04-05  2912280  
2022-04-06  2004175  
2022-04-07  1965237  
2022-04-08  1406219  
...             ...  
2022-08-22  2166778  
2022-08-23  1890327  
2022-08-24  1355374  
2022-08-25  1267482  
2022-08-26  1254230  

[100 rows x 6 columns]

In [65]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)

In [67]:
training_set_scaled

array([[0.0146515 ],
       [0.01635846],
       [0.01728306],
       ...,
       [0.89189189],
       [0.8903272 ],
       [0.88876243]])

In [76]:
X_train = []
y_train = []
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-10:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:end_ix+10]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

n_steps = 60
X_train, y_train = split_sequence(training_set_scaled, n_steps)

# X_train.append(training_set_scaled[0:60, 0])
# y_train.append(training_set_scaled[0, 0])

# for i in range(60, 2035):
#     print(i, training_set_scaled[i-60:i, 0], training_set_scaled[i, 0])
# X_train.append(training_set_scaled[i-60:i, 0])
# y_train.append(training_set_scaled[i, 0])
# X_train, y_train = np.array(X_train), np.array(y_train)
# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

array([[[0.1278094 ],
        [0.12937413],
        [0.13371266],
        ...,
        [0.15305833],
        [0.14295875],
        [0.13904694]],

       [[0.12937413],
        [0.13371266],
        [0.13143669],
        ...,
        [0.14295875],
        [0.13904694],
        [0.13790898]],

       [[0.13371266],
        [0.13143669],
        [0.1476529 ],
        ...,
        [0.13904694],
        [0.13790898],
        [0.14061167]],

       ...,

       [[0.86443814],
        [0.87133711],
        [0.8391181 ],
        ...,
        [0.86906118],
        [0.88997159],
        [0.89189189]],

       [[0.87133711],
        [0.8391181 ],
        [0.84580366],
        ...,
        [0.88997159],
        [0.89189189],
        [0.8903272 ]],

       [[0.8391181 ],
        [0.84580366],
        [0.86849216],
        ...,
        [0.89189189],
        [0.8903272 ],
        [0.88876243]]])

In [77]:
n_features = 1
X_train = X_train.reshape((X_train.shape[0], X_train.shape[1], n_features))
y_train = y_train.reshape((y_train.shape[0], y_train.shape[1], n_features))

In [47]:
y_train

array([[[0.1278094 ],
        [0.12937413],
        [0.13371266],
        ...,
        [0.15305833],
        [0.14295875],
        [0.13904694]],

       [[0.12937413],
        [0.13371266],
        [0.13143669],
        ...,
        [0.14295875],
        [0.13904694],
        [0.13790898]],

       [[0.13371266],
        [0.13143669],
        [0.1476529 ],
        ...,
        [0.13904694],
        [0.13790898],
        [0.14061167]],

       ...,

       [[0.86443814],
        [0.87133711],
        [0.8391181 ],
        ...,
        [0.86906118],
        [0.88997159],
        [0.89189189]],

       [[0.87133711],
        [0.8391181 ],
        [0.84580366],
        ...,
        [0.88997159],
        [0.89189189],
        [0.8903272 ]],

       [[0.8391181 ],
        [0.84580366],
        [0.86849216],
        ...,
        [0.89189189],
        [0.8903272 ],
        [0.88876243]]])

In [78]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense

In [80]:
model = Sequential()
model.add(LSTM(units=50,return_sequences=True,input_shape=(X_train.shape[1], 1)))
model.add(Dropout(0.2))
model.add(LSTM(units=50,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(units=50))
model.add(Dropout(0.2))
model.add(Dense(units=1))
model.compile(optimizer='adam',loss='mean_squared_error')
model.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
37/37 [==============================] - 8s 77ms/step - loss: 0.0338
Epoch 2/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0061
Epoch 3/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0058
Epoch 4/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0052
Epoch 5/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0058
Epoch 6/100
37/37 [==============================] - 3s 88ms/step - loss: 0.0043
Epoch 7/100
37/37 [==============================] - 3s 78ms/step - loss: 0.0044
Epoch 8/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0051
Epoch 9/100
37/37 [==============================] - 3s 77ms/step - loss: 0.0052
Epoch 10/100
37/37 [==============================] - 3s 78ms/step - loss: 0.0049
Epoch 11/100
37/37 [==============================] - 3s 78ms/step - loss: 0.0044
Epoch 12/100
37/37 [==============================] - 3s 78ms/step - loss: 0.0042
Epoch 13/100
37/37 [=====

# Make test predictions

# Predictions

In [90]:
# Get the last 60 days to predict the next 10
latest_60_days = X_train[-10:]

In [91]:
predicted_scaled_price = model.predict(latest_60_days)

1/1 [==============================] - 0s 33ms/step


In [92]:
predict_price = sc.inverse_transform(predicted_scaled_price)

In [94]:
predict_price

array([[801.8605 ],
       [799.9056 ],
       [799.86945],
       [802.04114],
       [803.1594 ],
       [799.40875],
       [791.2016 ],
       [781.73706],
       [774.1463 ],
       [770.5756 ]], dtype=float32)

# Visual representation